### PR TITLE
Primarily dropping python 2. Added pre-commit and github actions

### PR DESCRIPTION
**Pull request by marksweb**
Primarily dropping python 2.

Added pre-commit and github actions for flake8 & isort, plus pyupgrade in the pre-commit.

### CODE REVIEW

**Review by Aiky30 — APPROVED** [review]
Looks good to me.

**Comment by Aiky30** [comment]
The settings need to be added to run the linters and prevent merges without passes.

**Review by vinitkumar — APPROVED** [review]
Looks good to me. Let's get this merged and released 🚢  🚀

**Comment by marksweb** [comment]
> The settings need to be added to run the linters and prevent merges without passes.

Who's got settings access?

**Comment by marksweb** [comment]
Alongside these pre-commit setups, it'd be ideal to also include pre-commit CI to keep the versions of hooks updated;
https://github.com/marketplace/pre-commit-ci/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW42MTI2#pricing-and-setup

(This needs to be installed to the repos as we merge these hooks)

**Comment by marksweb** [comment]
@NicolaiRidani before I forget about this, need 2 jobs doing by someone with settings access to wrap this up.

**Pull request merged**
